/**
 * @file AnalysisResult.ts
 * @description Schema for the deep circuit analysis produced by the Python backend.
 *
 * Returned by `qforge.explainCircuit` command. Displayed in the ExplainPanel.
 */

import type { CircuitIR } from './CircuitIR';

/**
 * Breakdown of gate types and their occurrence counts.
 * Example: { "h": 1, "cx": 2, "measure": 2 }
 */
export type GateBreakdown = Record<string, number>;

/**
 * Full analysis result for a single quantum circuit.
 * Produced exclusively by the Python backend (circuit_analyzer.py).
 */
export interface AnalysisResult {
  /** The circuit this analysis was performed on. */
  readonly circuit: CircuitIR;

  /**
   * Human-readable summary of what the circuit does.
   * Generated by rule-based pattern matching in gate_explainer.py.
   * Example: "This circuit prepares a 2-qubit Bell State (|Φ+⟩)."
   */
  readonly summary: string;

  /**
   * Qiskit-computed circuit depth (longest critical path of gates).
   * More accurate than the TypeScript approximation.
   */
  readonly depth: number;

  /** Total number of gate operations (excluding barriers). */
  readonly gateCount: number;

  /** Breakdown of gate counts by gate name. */
  readonly gateBreakdown: GateBreakdown;

  /** Whether the circuit creates entanglement between qubits. */
  readonly isEntangled: boolean;

  /** Qubit labels for display (e.g., ["q_0", "q_1"] or custom register names). */
  readonly qubitLabels: readonly string[];

  /**
   * Circuit width in terms of two-qubit gate count.
   * Proxy for quantum complexity.
   */
  readonly twoQubitGateCount: number;

  /**
   * True if the circuit ends with measurements on all qubits.
   * Used to determine if this is a "complete" circuit.
   */
  readonly isComplete: boolean;
}
